# Generated by Django 5.0.4 on 2024-04-09 18:45

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'svg', 'png', 'webp', 'mp4', 'mpeg4', 'avi', 'mov', 'mkv', 'doc', 'docx', 'pdf', 'gif'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document'), ('gid', 'gif'), ('other', 'other')], max_length=20, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', ckeditor.fields.RichTextField(verbose_name='main text')),
                ('main_phone_number', models.CharField(max_length=20, verbose_name='main_phone_number')),
                ('blog_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='media.media', verbose_name='blog image')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='media.media', verbose_name='main image')),
                ('other_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='media.media', verbose_name='Other images')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
